### ISSUE TITLE
test example doesn't compile

### ISSUE THREAD

**Issue by alhanashi7** [mcci-catena/MCCI-WattNode-Modbus#7]
hi
can I have your support, please? 
I need the code to collect data from WattNode meter

**Comment by terrillmoore** [comment]
Hi @alhanashi7 -- MCCI has not open-sourced our WattNode code at this time. If you will contact MCCI via email using the contact info at https://mcci.com, we can see if we can help you. Best regards, --Terry

**Comment by terrillmoore** [comment]
Hi again, thanks for mailing us. In your mail, you report that the sample app doesn't compile for you. 

I've tested and confirmed that the test doesn't compile for me either. I'll investigate now.

**Comment by terrillmoore** [comment]
See Issue #1 -- without CI, this kind of problem is inevitable.

@alhanashi7 very sorry. When I applied 42ede720cc6b06e7cbc5ac886b92c13a8f03d7f6, I neglected to update the `test` sketch.

In your code, you must reference the object `McciWattNodeModbus::WattNode_WNC` or `McciWattNodeModbus::WattNode_WND` to reference any of the static methods. In the sample sketch, I now have:

```c++
using WattNodeModbus = McciWattNodeModbus::WattNode_WNC;
```

You can use any name you like instead of `WattNodeModbus`.

Pull request #8 corrects this. I'll file bugs to add more documentation on this as well.
